version: "3"

tasks:
  gen_schemas:
    cmds:
      - nix eval --impure --json --file src/nixos_module_schema.nix > src/nixos_module_schema.json
      - nix eval --impure --json --file src/home_manager_schema.nix > src/home_manager_schema.json
