import ./lib/maketest.nix {
  type = "completion";
  disabled = true;
  source = ''
    { ^}
  '';
  expected = [
    "nixops"
    "ids"
    "gtk"
    "services"
    "powerManagement"
    "system"
    "docker-containers"
    "security"
    "passthru"
    "programs"
    "zramSwap"
    "dysnomia"
    "virtualisation"
    "jobs"
    "openstack"
    "nesting"
    "systemd"
    "hardware"
    "environment"
    "nixpkgs"
    "sound"
    "power"
    "documentation"
    "appstream"
    "containers"
    "time"
    "warnings"
    "snapraid"
    "assertions"
    "location"
    "i18n"
    "stubby"
    "nix"
    "xdg"
    "ec2"
    "users"
    "boot"
    "lib"
    "meta"
    "gnu"
    "fileSystems"
    "krb5"
    "specialisation"
    "fonts"
    "networking"
    "swapDevices"
    "qt5"
    "console"
  ];
}