[package]
name = "eval"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
salsa = { git = "https://github.com/salsa-rs/salsa.git", package = "salsa-2022" }
sorted-vec = "0.8.3"
syntax = { path = "../syntax" }
