name: "Test"
on:
  pull_request:
  push:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v17
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: cachix/cachix-action@v11
      with:
        name: jm8
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: nix build && nix develop -c bash -c './result/nix-analyzer-test tests/*.nix && ./result/parsertest'